# -*- coding: utf-8 -*-
"""final fiuba

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLgsx8De18yHr2VtQPrJM1sxRN84ITTw
"""

datostren=[]
def ingreso(datostren):
    
        
    continuar=True
    while continuar:
        viajes=[]
        codigotren=input("Ingrese el nombre del codigo de viaje: ")

        operador= input("Ingrese el nombre del operador: ")
        # nombreserv=input("Ingrese el nombre del servicio: ")
        # origen=input("Ingrese el nombre de origen: ").lower
        # destino=input("Ingrese el nombre del destino: ").lower
        # estado=input("Ingrese el estado del viaje(en tiempo, estimado o demorado): ").lower
        
        while operador.isalpha() == False:
                operador = input("Ingrese el nombre con letras del operador: ") 
                
        nombreserv=input("Ingrese el nombre del servicio: ")
                
        while nombreserv.isalpha() == False:
                 nombreserv=input("Ingrese el nombre del servicio: ")
        
        estado=input("Ingrese el estado del viaje(Atiempo, estimado o demorado): ")
                
        while estado.isalpha() == False:
                estado=input("Ingrese el estado del viaje(Atiempo, estimado o demorado): ")
                
        origen=input("Ingrese el nombre de origen: ")
        
        while origen.isalpha() == False:
                origen=input("Ingrese el nombre de origen: ")
                
        destino=input("Ingrese el nombre del destino: ")
                
        while destino.isalpha() == False:
                destino=input("Ingrese el nombre del destino: ")
                
                
        errores = True
        while errores:
                try: 
                    horariodesalida= int(input("Ingrese el horario de salida como HHMM: "))
                    horariodellegada= int(input("Ingrese el horario de llegada como HHMM: "))
                    if horariodesalida <0:
                        print("Tiene que ser un numero positivo")
                    errores = False
                    if horariodellegada <0:
                        print("Tiene que ser un numero positivo")
                    errores = False
                except ValueError:
                    print("verifique los valores ingresados")
                    errores = True
                    
        
        viajes.append(codigotren)
        viajes.append(operador)
        viajes.append(nombreserv)
        viajes.append(estado)
        viajes.append(origen)
        viajes.append(destino)
        viajes.append(horariodesalida)
        viajes.append(horariodellegada)
        datostren.append(viajes)
        print(viajes)
        
  
        print("¿Desea seguir agregando viajes? ")
        respuesta=input("s/n: ").lower()
        while respuesta != "s" and respuesta != "n":
                print("Solo puede agregar s/n")
        if respuesta=="s":
            continuar = True
        elif respuesta =="n":
            continuar = False

ingreso(datostren)